services:
  db:
    image: postgres:15
    container_name: svicmajster_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: svicmajster_mqtt
    restart: always
    ports:
    - "1883:1883"
    - "9001:9001"
    volumes:
    - ./mosquitto/config:/mosquitto/config
    - ./mosquitto/data:/mosquitto/data
    - ./mosquitto/log:/mosquitto/log

  faceid:
    build:
      # kontekst je koren repozitorija, da dosezemo skupni requirements.txt
      context: ..
      dockerfile: RAI/face-service/Dockerfile
    container_name: svicmajster_face
    restart: always
    ports:
      - "8000:8000"
    environment:
      - FACE_THRESHOLD=50
      - ORV_PATH=/app/orv
    volumes:
      - face_models:/app/models
      # deljene ORV skripte (samo za branje)
      - ../ORV:/app/orv:ro

volumes:
  postgres_data:
  face_models: