name: Python Testi (ORV)

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'ORV/**'
      - 'SA/tests/python/**'

  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'ORV/**'
      - 'SA/tests/python/**'

jobs:
  python-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Python okolje setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Namestitev sys knjiznic za OpenCV
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1

      - name: Namestitev Python odvisnosti
        run: |
          python -m pip install --upgrade pip
          pip install opencv-contrib-python numpy pytest

      - name: Zagon Python testov samo za ORV
        run: |
          pytest SA/tests/python/